## Python Pandas - Data Manipulation

In [188]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [3]:
my_list

[10, 20, 30, 40]

In [4]:
pd.DataFrame(my_list)

0
0  10
1  20
2  30
3  40

In [6]:
df = pd.DataFrame(my_list, columns= ["Age"])

In [7]:
df

Age
0   10
1   20
2   30
3   40

In [8]:
m = np.arange(1,10)

In [9]:
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
df.values #Numpy Array

array([[10],
       [20],
       [30],
       [40]], dtype=int64)

In [13]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
df.columns

Index(['Age'], dtype='object')

In [64]:
m = np.arange(1,100)

In [65]:
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [66]:
m = np.arange(1,100).reshape((11,9))

In [67]:
m

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
m[2]

array([19, 20, 21, 22, 23, 24, 25, 26, 27])

In [69]:
m= np.arange(1,10).reshape((3,3))

In [70]:
m[1][2]*m[1][1]

30

In [71]:
pd.DataFrame(m, columns = ["Age1","Age2","Age3"])

Age1  Age2  Age3
0     1     2     3
1     4     5     6
2     7     8     9

In [72]:
df = pd.DataFrame(m, columns = ["Age1","Age2","Age3"])

In [73]:
df.shape

(3, 3)

In [74]:
df.ndim

2

In [75]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [76]:
df.columns

Index(['Age1', 'Age2', 'Age3'], dtype='object')

In [77]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
df.index = ["Air","Water","Soil"]

In [82]:
df.columns

Index(['Age1', 'Age2', 'Age3'], dtype='object')

In [83]:
df.T

Air  Water  Soil
Age1    1      4     7
Age2    2      5     8
Age3    3      6     9

In [84]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
df.index = ["a","b","c"]

In [86]:
df.columns

Index(['Age1', 'Age2', 'Age3'], dtype='object')

In [87]:
df

Age1  Age2  Age3
a     1     2     3
b     4     5     6
c     7     8     9

In [88]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
df = sns.load_dataset("car_crashes")

In [91]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   total           51 non-null     float64
 1   speeding        51 non-null     float64
 2   alcohol         51 non-null     float64
 3   not_distracted  51 non-null     float64
 4   no_previous     51 non-null     float64
 5   ins_premium     51 non-null     float64
 6   ins_losses      51 non-null     float64
 7   abbrev          51 non-null     object 
dtypes: float64(7), object(1)
memory usage: 3.3+ KB


In [92]:
df.shape

(51, 8)

In [96]:
df.dtypes

total             float64
speeding          float64
alcohol           float64
not_distracted    float64
no_previous       float64
ins_premium       float64
ins_losses        float64
abbrev             object
dtype: object

In [97]:
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [98]:
df.tail()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
46      153.72     VA  
47      111.62     WA  
48      152.56     WV  
49      106.62     WI  
50      122.04     WY

In [99]:
df.tail(10)

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
41   19.4     6.014    6.402          19.012       16.684       669.31   
42   19.5     4.095    5.655          15.990       15.795       767.91   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
44   11.3     4.859    1.808           9.944       10.848       809.38   
45   13.6     4.080    4.080          13.056       12.920       716.20   
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
41       96.87     SD  
42      155.57     TN  
43      156.83     TX  
44      109.48     UT  
45      109.61     VT  
46      153.72     VA  
47      111.62     WA  
48      152.56     WV  
49      106.62     WI  
50      122.04     WY

In [100]:
df.head(10)

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   
5   13.6     5.032    3.808          10.744       12.920       835.50   
6   10.8     4.968    3.888           9.396        8.856      1068.73   
7   16.2     6.156    4.860          14.094       16.038      1137.87   
8    5.9     2.006    1.593           5.900        5.900      1273.89   
9   17.9     3.759    5.191          16.468       16.826      1160.13   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA  
5      139.91     CO  
6      167.02     CT  
7      151.48     DE  
8      136.05     DC  
9      144.18     FL

In [105]:
df[["total","speeding"]]

total  speeding
0    18.8     7.332
1    18.1     7.421
2    18.6     6.510
3    22.4     4.032
4    12.0     4.200
5    13.6     5.032
6    10.8     4.968
7    16.2     6.156
8     5.9     2.006
9    17.9     3.759
10   15.6     2.964
11   17.5     9.450
12   15.3     5.508
13   12.8     4.608
14   14.5     3.625
15   15.7     2.669
16   17.8     4.806
17   21.4     4.066
18   20.5     7.175
19   15.1     5.738
20   12.5     4.250
21    8.2     1.886
22   14.1     3.384
23    9.6     2.208
24   17.6     2.640
25   16.1     6.923
26   21.4     8.346
27   14.9     1.937
28   14.7     5.439
29   11.6     4.060
30   11.2     1.792
31   18.4     3.496
32   12.3     3.936
33   16.8     6.552
34   23.9     5.497
35   14.1     3.948
36   19.9     6.368
37   12.8     4.224
38   18.2     9.100
39   11.1     3.774
40   23.9     9.082
41   19.4     6.014
42   19.5     4.095
43   19.4     7.760
44   11.3     4.859
45   13.6     4.080
46   12.7     2.413
47   10.6     4.452
48   23.8     8.092
49   13.8     4.968
50   17.4     7.308

In [107]:
df[["total"]].head()

total
0   18.8
1   18.1
2   18.6
3   22.4
4   12.0

In [109]:
df[["alcohol","total"]].head()

alcohol  total
0    5.640   18.8
1    4.525   18.1
2    5.208   18.6
3    5.824   22.4
4    3.360   12.0

In [114]:
df["alcohol"].head() #Serie

0    5.640
1    4.525
2    5.208
3    5.824
4    3.360
Name: alcohol, dtype: float64

In [117]:
df[["alcohol"]].head() #dataframe

alcohol
0    5.640
1    4.525
2    5.208
3    5.824
4    3.360

In [119]:
df.iloc[10:13]

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
10   15.6     2.964    3.900          14.820       14.508       913.15   
11   17.5     9.450    7.175          14.350       15.225       861.18   
12   15.3     5.508    4.437          13.005       14.994       641.96   

    ins_losses abbrev  
10      142.80     GA  
11      120.92     HI  
12       82.75     ID

In [120]:
df.iloc[0:3][["not_distracted","alcohol"]]

not_distracted  alcohol
0          18.048    5.640
1          16.290    4.525
2          15.624    5.208

In [123]:
df.iloc[2:3]

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
2   18.6      6.51    5.208          15.624       17.856       899.47   

   ins_losses abbrev  
2      110.35     AZ

In [124]:
df.iloc[2:3].T

2
total             18.6
speeding          6.51
alcohol          5.208
not_distracted  15.624
no_previous     17.856
ins_premium     899.47
ins_losses      110.35
abbrev              AZ

In [125]:
df.iloc[2:3][["speeding"]]

speeding
2      6.51

In [129]:
df.iloc[0,0]

18.8

In [131]:
df.iloc[0,0] + df.iloc[0,0]

37.6

In [132]:
df.loc[2:3]

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   

   ins_losses abbrev  
2      110.35     AZ  
3      142.39     AR

In [133]:
df.loc[2:3][["speeding"]]

speeding
2     6.510
3     4.032

In [134]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [136]:
# a[a>3]

In [139]:
df[df["speeding"]>5].head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
5   13.6     5.032    3.808          10.744       12.920       835.50   
7   16.2     6.156    4.860          14.094       16.038      1137.87   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
5      139.91     CO  
7      151.48     DE

In [140]:
df["Esin"] = 10

In [141]:
df

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0    18.8     7.332    5.640          18.048       15.040       784.55   
1    18.1     7.421    4.525          16.290       17.014      1053.48   
2    18.6     6.510    5.208          15.624       17.856       899.47   
3    22.4     4.032    5.824          21.056       21.280       827.34   
4    12.0     4.200    3.360          10.920       10.680       878.41   
5    13.6     5.032    3.808          10.744       12.920       835.50   
6    10.8     4.968    3.888           9.396        8.856      1068.73   
7    16.2     6.156    4.860          14.094       16.038      1137.87   
8     5.9     2.006    1.593           5.900        5.900      1273.89   
9    17.9     3.759    5.191          16.468       16.826      1160.13   
10   15.6     2.964    3.900          14.820       14.508       913.15   
11   17.5     9.450    7.175          14.350       15.225       861.18   
12   15.3     5.508    4.437          13.005       14.994       641.96   
13   12.8     4.608    4.352          12.032       12.288       803.11   
14   14.5     3.625    4.205          13.775       13.775       710.46   
15   15.7     2.669    3.925          15.229       13.659       649.06   
16   17.8     4.806    4.272          13.706       15.130       780.45   
17   21.4     4.066    4.922          16.692       16.264       872.51   
18   20.5     7.175    6.765          14.965       20.090      1281.55   
19   15.1     5.738    4.530          13.137       12.684       661.88   
20   12.5     4.250    4.000           8.875       12.375      1048.78   
21    8.2     1.886    2.870           7.134        6.560      1011.14   
22   14.1     3.384    3.948          13.395       10.857      1110.61   
23    9.6     2.208    2.784           8.448        8.448       777.18   
24   17.6     2.640    5.456           1.760       17.600       896.07   
25   16.1     6.923    5.474          14.812       13.524       790.32   
26   21.4     8.346    9.416          17.976       18.190       816.21   
27   14.9     1.937    5.215          13.857       13.410       732.28   
28   14.7     5.439    4.704          13.965       14.553      1029.87   
29   11.6     4.060    3.480          10.092        9.628       746.54   
30   11.2     1.792    3.136           9.632        8.736      1301.52   
31   18.4     3.496    4.968          12.328       18.032       869.85   
32   12.3     3.936    3.567          10.824        9.840      1234.31   
33   16.8     6.552    5.208          15.792       13.608       708.24   
34   23.9     5.497   10.038          23.661       20.554       688.75   
35   14.1     3.948    4.794          13.959       11.562       697.73   
36   19.9     6.368    5.771          18.308       18.706       881.51   
37   12.8     4.224    3.328           8.576       11.520       804.71   
38   18.2     9.100    5.642          17.472       16.016       905.99   
39   11.1     3.774    4.218          10.212        8.769      1148.99   
40   23.9     9.082    9.799          22.944       19.359       858.97   
41   19.4     6.014    6.402          19.012       16.684       669.31   
42   19.5     4.095    5.655          15.990       15.795       767.91   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
44   11.3     4.859    1.808           9.944       10.848       809.38   
45   13.6     4.080    4.080          13.056       12.920       716.20   
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  Esin  
0       145.08     AL    10  
1       133.93     AK    10  
2       110.35     AZ    10  
3       142.39     AR    10  
4    

In [142]:
df.T

0        1       2       3       4       5        6   \
total             18.8     18.1    18.6    22.4    12.0    13.6     10.8   
speeding         7.332    7.421    6.51   4.032     4.2   5.032    4.968   
alcohol           5.64    4.525   5.208   5.824    3.36   3.808    3.888   
not_distracted  18.048    16.29  15.624  21.056   10.92  10.744    9.396   
no_previous      15.04   17.014  17.856   21.28   10.68   12.92    8.856   
ins_premium     784.55  1053.48  899.47  827.34  878.41   835.5  1068.73   
ins_losses      145.08   133.93  110.35  142.39  165.63  139.91   167.02   
abbrev              AL       AK      AZ      AR      CA      CO       CT   
Esin                10       10      10      10      10      10       10   

                     7        8        9   ...      41      42       43  \
total              16.2      5.9     17.9  ...    19.4    19.5     19.4   
speeding          6.156    2.006    3.759  ...   6.014   4.095     7.76   
alcohol            4.86    1.593    5.191  ...   6.402   5.655    7.372   
not_distracted   14.094      5.9   16.468  ...  19.012   15.99   17.654   
no_previous      16.038      5.9   16.826  ...  16.684  15.795   16.878   
ins_premium     1137.87  1273.89  1160.13  ...  669.31  767.91  1004.75   
ins_losses       151.48   136.05   144.18  ...   96.87  155.57   156.83   
abbrev               DE       DC       FL  ...      SD      TN       TX   
Esin                 10       10       10  ...      10      10       10   

                    44      45      46      47      48      49      50  
total             11.3    13.6    12.7    10.6    23.8    13.8    17.4  
speeding         4.859    4.08   2.413   4.452   8.092   4.968   7.308  
alcohol          1.808    4.08   3.429   3.498   6.664   4.554   5.568  
not_distracted   9.944  13.056  11.049   8.692  23.086   5.382  14.094  
no_previous     10.848   12.92  11.176   9.116  20.706  11.592   15.66  
ins_premium     809.38   716.2  768.95  890.03  992.61  670.31  791.14  
ins_losses      109.48  109.61  153.72  111.62  152.56  106.62  122.04  
abbrev              UT      VT      VA      WA      WV      WI      WY  
Esin                10      10      10      10      10      10      10  

[9 rows x 51 columns]

## Exercises

### Exercises 1 

In [145]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  Esin  
0      145.08     AL    10  
1      133.93     AK    10  
2      110.35     AZ    10  
3      142.39     AR    10  
4      165.63     CA    10

In [146]:
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev', 'Esin'],
      dtype='object')

In [151]:
[col.upper() for col in df.columns]

['TOTAL',
 'SPEEDING',
 'ALCOHOL',
 'NOT_DISTRACTED',
 'NO_PREVIOUS',
 'INS_PREMIUM',
 'INS_LOSSES',
 'ABBREV',
 'ESIN']

In [164]:
new_columns = [col.lower() for col in df.columns]

In [165]:
df.columns = new_columns

In [166]:
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev', 'esin'],
      dtype='object')

In [167]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  esin  
0      145.08     AL    10  
1      133.93     AK    10  
2      110.35     AZ    10  
3      142.39     AR    10  
4      165.63     CA    10

## Python List Comprehension

In [168]:
[col.upper() for col in df.columns]

['TOTAL',
 'SPEEDING',
 'ALCOHOL',
 'NOT_DISTRACTED',
 'NO_PREVIOUS',
 'INS_PREMIUM',
 'INS_LOSSES',
 'ABBREV',
 'ESIN']

In [169]:
["NUMBER_" + col.upper() if df[col].dtype != "O" else col.lower() for col in df.columns]

['NUMBER_TOTAL',
 'NUMBER_SPEEDING',
 'NUMBER_ALCOHOL',
 'NUMBER_NOT_DISTRACTED',
 'NUMBER_NO_PREVIOUS',
 'NUMBER_INS_PREMIUM',
 'NUMBER_INS_LOSSES',
 'abbrev',
 'NUMBER_ESIN']

## Python Queries

In [170]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  esin  
0      145.08     AL    10  
1      133.93     AK    10  
2      110.35     AZ    10  
3      142.39     AR    10  
4      165.63     CA    10

In [171]:
df["total"].sum()

805.2999999999998

In [181]:
df.groupby(["abbrev"]).agg({"total": ["count","sum"]}).head()

total      
       count   sum
abbrev            
AK         1  18.1
AL         1  18.8
AR         1  22.4
AZ         1  18.6
CA         1  12.0

In [185]:
df.groupby(["abbrev"]).agg({"speeding": ["sum","count","mean"]}).head()

speeding             
            sum count   mean
abbrev                      
AK        7.421     1  7.421
AL        7.332     1  7.332
AR        4.032     1  4.032
AZ        6.510     1  6.510
CA        4.200     1  4.200

## Titanic Dataset

In [195]:
df = sns.load_dataset("titanic")

In [196]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [198]:
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [199]:
df["who"].value_counts()

man      537
woman    271
child     83
Name: who, dtype: int64

In [201]:
df.nunique() # Number of unique category

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [203]:
df["sibsp"].value_counts()

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: sibsp, dtype: int64

In [206]:
df[["pclass","parch"]].nunique()

pclass    3
parch     7
dtype: int64

In [207]:
df[df["class"] == "Third"].head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
2         1       3  female  26.0      0      0   7.9250        S  Third   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
2  woman       False  NaN  Southampton   yes   True  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
7  child       False  NaN  Southampton    no  False

In [208]:
df[df["class"] == "Third"].shape

(491, 15)

In [213]:
df[df["class"] != "Third"][["who"]].head()

who
1   woman
3   woman
6     man
9   child
11  woman

In [217]:
df[(df["age"] <20) & (df["sex"] == "male")].head()

survived  pclass   sex   age  sibsp  parch      fare embarked  class  \
7          0       3  male   2.0      3      1   21.0750        S  Third   
16         0       3  male   2.0      4      1   29.1250        Q  Third   
27         0       1  male  19.0      3      2  263.0000        S  First   
50         0       3  male   7.0      4      1   39.6875        S  Third   
59         0       3  male  11.0      5      2   46.9000        S  Third   

      who  adult_male deck  embark_town alive  alone  
7   child       False  NaN  Southampton    no  False  
16  child       False  NaN   Queenstown    no  False  
27    man        True    C  Southampton    no  False  
50  child       False  NaN  Southampton    no  False  
59  child       False  NaN  Southampton    no  False

In [219]:
df[(df["fare"] >1000) |(df["age"] >70)].head()

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
96          0       1  male  71.0      0      0  34.6542        C  First  man   
116         0       3  male  70.5      0      0   7.7500        Q  Third  man   
493         0       1  male  71.0      0      0  49.5042        C  First  man   
630         1       1  male  80.0      0      0  30.0000        S  First  man   
851         0       3  male  74.0      0      0   7.7750        S  Third  man   

     adult_male deck  embark_town alive  alone  
96         True    A    Cherbourg    no   True  
116        True  NaN   Queenstown    no   True  
493        True  NaN    Cherbourg    no   True  
630        True    A  Southampton   yes   True  
851        True  NaN  Southampton    no   True

In [221]:
df.isnull().any()

survived       False
pclass         False
sex            False
age             True
sibsp          False
parch          False
fare           False
embarked        True
class          False
who            False
adult_male     False
deck            True
embark_town     True
alive          False
alone          False
dtype: bool

In [222]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [224]:
df_new = df.drop("who", axis = 1) # inplace = True (default)

In [226]:
df_new

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

     adult_male deck  embark_town alive  alone  
0          True  NaN  Southampton    no  False  
1         False    C    Cherbourg   yes  False  
2         False  NaN  Southampton   yes   True  
3         False    C  Southampton   yes  False  
4          True  NaN  Southampton    no   True  
..          ...  ...          ...   ...    ...  
886        True  NaN  Southampton    no   True  
887       False    B  Southampton   yes   True  
888       False  NaN  Southampton    no  False  
889        True    C    Cherbourg   yes   True  
890        True  NaN   Queenstown    no   True  

[891 rows x 14 columns]

In [228]:
df["embark_town"].value_counts()

Southampton    644
Cherbourg      168
Queenstown      77
Name: embark_town, dtype: int64

In [229]:
df["embark_town"].mode()

0    Southampton
Name: embark_town, dtype: object

In [230]:
df["age"].median()

28.0

In [233]:
df["age"].fillna(df["age"].median()).tail(20)

871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878    28.0
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, dtype: float64

In [252]:
df[df["sex"] == "male"]["age"].median()       

29.0

In [253]:
df[df["sex"] == "female"]["age"].median()

27.0

[df.fillna(df.groupby("sex").agg({"age": ["median"]})) if df[df["sex"] == "female" else df.fillna(df.groupby("sex").agg({"age": ["median"]}))  for col in df.columns]

In [257]:
df["age"].fillna(df["age"].median(), inplace=True)

In [258]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [260]:
df["age"].mean()

29.36158249158249

In [262]:
df.groupby("sex").agg({"age": ["mean"]})

age
             mean
sex              
female  27.929936
male    30.140676

In [266]:
df.groupby(["alone","sex"]).agg({"survived": ["sum","count","mean"]})

survived                
                  sum count      mean
alone sex                            
False female      134   188  0.712766
      male         45   166  0.271084
True  female       99   126  0.785714
      male         64   411  0.155718

In [267]:
df.groupby(["alone","sex"]).agg({"survived": ["sum","count","mean"]}).index

MultiIndex([(False, 'female'),
            (False,   'male'),
            ( True, 'female'),
            ( True,   'male')],
           names=['alone', 'sex'])

In [268]:
df.groupby(["alone","sex"]).agg({"survived": ["sum","count","mean"]}).count()

survived  sum      4
          count    4
          mean     4
dtype: int64

In [271]:
df.groupby("pclass")["age"].count() #not dataframe

pclass
1    216
2    184
3    491
Name: age, dtype: int64

In [273]:
df.groupby(["pclass"]).agg({"fare":  ["sum","count","mean"]})

fare                 
               sum count       mean
pclass                             
1       18177.4125   216  84.154687
2        3801.8417   184  20.662183
3        6714.6951   491  13.675550

In [274]:
df.groupby(["sex","pclass"]).agg({"fare": "mean"})

fare
sex    pclass            
female 1       106.125798
       2        21.970121
       3        16.118810
male   1        67.226127
       2        19.741782
       3        12.661633

In [275]:
df.groupby(["sex","pclass", "alone"]).agg({"fare": "mean"})

fare
sex    pclass alone            
female 1      False  106.219445
              True   105.960538
       2      False   27.916761
              True    13.793491
       3      False   21.750298
              True     8.234727
male   1      False  103.488123
              True    44.501943
       2      False   30.850811
              True    14.187268
       3      False   22.693076
              True     9.507808

In [276]:
df.groupby(["sex","pclass", "alone"]).agg({"fare": "mean"}).T

sex         female                                                         \
pclass           1                      2                     3             
alone        False        True      False       True      False      True   
fare    106.219445  105.960538  27.916761  13.793491  21.750298  8.234727   

sex           male                                                        
pclass           1                     2                     3            
alone        False       True      False       True      False      True  
fare    103.488123  44.501943  30.850811  14.187268  22.693076  9.507808

In [277]:
df.groupby(["sex","pclass", "alone"]).agg({"fare": "mean"}).T.to_csv("Summary.csv", sep = "|")

In [279]:
df.groupby(["sex","pclass", "alone"]).agg({"fare": "mean"}).T.to_csv("Summary_1.csv", sep = "|",decimal = ",")

In [280]:
df.sort_values("fare", ascending=False).head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
679         1       1    male  36.0      0      1  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
27          0       1    male  19.0      3      2  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone  
258  woman       False  NaN    Cherbourg   yes   True  
737    man        True    B    Cherbourg   yes   True  
679    man        True    B    Cherbourg   yes  False  
88   woman       False    C  Southampton   yes  False  
27     man        True    C  Southampton    no  False

In [290]:
agg_df = df.groupby(["who","embark_town","alive","alone"]).agg({"age" : ["mean", "count"]}).head(20)

In [291]:
agg_df.head(20)

age      
                                    mean count
who   embark_town alive alone                 
child Cherbourg   no    False  12.833333     3
                        True   11.000000     1
                  yes   False   5.910000    12
                        True   14.000000     2
      Queenstown  no    False   5.250000     4
                  yes   True   15.000000     1
      Southampton no    False   6.440000    25
                        True   14.000000     1
                  yes   False   4.977273    33
                        True    5.000000     1
man   Cherbourg   no    False  34.342105    19
                        True   32.733333    45
                  yes   False  34.000000    12
                        True   30.857143    14
      Queenstown  no    False  32.666667     6
                        True   31.892857    28
                  yes   False  28.000000     1
                        True   28.500000     2
      Southampton no    False  32.243590    78
                        True   31.289377   273

## Apply & Lambda

In [292]:
df["Esin"] = 30

In [293]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  Esin  
0    man        True  NaN  Southampton    no  False    30  
1  woman       False    C    Cherbourg   yes  False    30  
2  woman       False  NaN  Southampton   yes   True    30  
3  woman       False    C  Southampton   yes  False    30  
4    man        True  NaN  Southampton    no   True    30

In [294]:
df["Esin"]

0      30
1      30
2      30
3      30
4      30
       ..
886    30
887    30
888    30
889    30
890    30
Name: Esin, Length: 891, dtype: int64

In [297]:
df["age_flag"] = df["age"].apply(lambda x: "30-" if x<30 else "30+" )

In [299]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  Esin age_flag  
0    man        True  NaN  Southampton    no  False    30      30-  
1  woman       False    C    Cherbourg   yes  False    30      30+  
2  woman       False  NaN  Southampton   yes   True    30      30-  
3  woman       False    C  Southampton   yes  False    30      30+  
4    man        True  NaN  Southampton    no   True    30      30+

In [301]:
df.drop("Esin",axis = 1, inplace=True)